version: "3"
services:
  redis-master1:
    image: redis:5.0
    container_name: redis-master1
    working_dir: /redis
    ports:
      - "36379:36379"
      - "46379:46379"
    restart: always
    volumes: ["./redis-master1:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-master2:
    image: redis:5.0
    working_dir: /redis
    container_name: redis-master2
    ports:
      - "36380:36380"
      - "46380:46380"
    restart: always
    volumes: ["./redis-master2:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-master3:
    image: redis:5.0
    container_name: redis-master3
    working_dir: /redis
    ports:
      - "36381:36381"
      - "46381:46381"
    restart: always
    volumes: ["./redis-master3:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-slave1:
    image: redis:5.0
    container_name: redis-slave1
    working_dir: /redis
    ports:
      - "36382:36382"
      - "46382:46382"
    restart: always
    volumes: ["./redis-slave1:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-slave2:
    image: redis:5.0
    working_dir: /redis
    container_name: redis-slave2
    ports:
      - "36383:36383"
      - "46383:46383"
    restart: always
    volumes: ["./redis-slave2:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-slave3:
    image: redis:5.0
    container_name: redis-slave3
    working_dir: /redis
    ports:
      - "36384:36384"
      - "46384:46384"
    restart: always
    volumes: ["./redis-slave3:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]