version: "3"
services:
  redis-master1: 
    image: redis:5.0
    container_name: redis-master1
    working_dir: /redis
    network_mode: host
    restart: always
    volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-master1:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-master2:
    image: redis:5.0
    working_dir: /redis
    container_name: redis-master2
    network_mode: host
    restart: always
    volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-master2:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-master3:
    image: redis:5.0
    container_name: redis-master3
    working_dir: /redis
    network_mode: host
    restart: always
    volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-master3:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-slave1:
    image: redis:5.0
    network_mode: host
    container_name: redis-slave1
    working_dir: /redis
    restart: always
    volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-slave1:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-slave2:
    image: redis:5.0
    working_dir: /redis
    container_name: redis-slave2
    network_mode: host
    restart: always
    volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-slave2:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]
  redis-slave3:
    image: redis:5.0
    container_name: redis-slave3
    working_dir: /redis
    network_mode: host
    restart: always
    volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-slave3:/redis"]
    entrypoint: [redis-server, /redis/redis.conf]